spring:
  application:
    name: consumer
  cloud:
    stream:
      bindings:
        receiveResponse-in-0:
          destination: uppercase-response
          group: processor
          consumer:
            maxAttempts: 10
      rabbit:
        bindings:
          receiveResponse-in-0:
            consumer:
              auto-bind-dlq: true
              enableDlq: true
              dlqTtl: 5000
              republishToDlq: true
server:
  port: 2032
instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}